const DEFAULT_START = "Hey! Whatsup!";
const DEFAULT_FOLLOW = "Ehh! Leave me alone!";

export const PLAYERDIALOGS = {
    Frank: {
        follows:["Hey Frank! I'm great.", 
                 "I'm a bit busy with my engineering exams. What about you?", 
                 "Oh wow! That's awesome.", 
                 "Ohh, thanks for informing :). I'll probably go now.", 
                 "BBye, Takecare."],
        starts:[DEFAULT_START, 
                "Yup. He told me about that markov tribe."],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Dad: {
        follows:["It feels great to be back home. You look worried dad. Is everything fine?", 
                 "Yeah! The town seems a bit different. Someone refused to play Roshambo with me coz I was not on his level! I didn't get it.",
                 "Markov tribe? That's an interesting name. And what are the new rules?",
                 "And...",
                 "Okay! Now I get it. But this isn't great for our town. We always had a 'free Roshambo for all' motto.",
                 "How can we do that?",
                 "I can do that dad. But I need some practice.",
                 "Okay dad! I'll go and practice now. Big task ahead.",
                 "Even I missed Joey. Sure, I'll play with him.",
                 "Thats amazing! I'll grab an Eclair from there.",
                ],
        starts:["Hey Dad! Whatsup?"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Joey: {
        follows:[],
        starts:[],
        battleAccept:["Okay Joey. Let's battle!"],
        battleAsk:["Hey Joey! you wanna play?"],
        battleWin:["Nevermind...."],
        battleLose:["I always let you win."],
    },

    Tia: {
        follows:["Hey Tia! I'm great. Came here to get some eclairs.", 
                 "Why so? I see the bakery is open.", 
                 "Its not their bakery! why are we being forced to battle him?", 
                 "Okay, I'll go inside and defeat him.",
                 "Sure, I'll do that. See you!",
                ],
        starts:["Hey Tia! Whatsup?"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Nathan: {
        follows:[],
        starts:[],
        battleAccept:["Yeah sure, lets go!"],
        battleAsk:["Hey! do you wanna battle?"],
        battleWin:["Thanks mate!"],
        battleLose:["I'll be back in no time. See you then."],
    },

    John: {
        follows:[],
        starts:[],
        battleAccept:["Yeah sure, lets go!"],
        battleAsk:["Hey! do you wanna battle?"],
        battleWin:["Thanks mate!"],
        battleLose:["I'll be back in no time. See you then."],
    },

    Samantha: {
        follows:[],
        starts:[],
        battleAccept:["Yeah sure, who doesn't like a freebie ;)"],
        battleAsk:["Hey! do you wanna battle?"],
        battleWin:["Thanks! I think I am ready to defeat him.", "Great! Now I have 2 reasons to defeat him haha."],
        battleLose:["I'll be back in no time. See you then."],
    },

    Eden:{

        follows:[],
        starts:[],
        battleAccept:["I'm $PLAYERNAME. I'm not new, you are new here. Btw, I came here for an eclair.",
                      "Really? I thought I need to have a Roshambo battle with you. Guess you are not that bad.",
                      "And I thought for a moment that the tribe isn't that bad. Nevertheless, I can defeat you, pretty easily.",
                      "Yup, lets go!!!"],
        battleAsk:["I want to challenge you for a battle!"],
        battleWin:["I'll take care of your boss later. I need my eclair now. Step aside.", 
                   "But you said so. And I believed you!",
                   "F*** man. What else can I expect from the tribe! Where can I find your boss?",
                   "Ughhhhhh."],
        battleLose:["I'll be back in no time. "],
    },

    Tracer: {
        follows:["Hey Tracer. I'm looking for the tribe boss. Do you know where he lives?",
                 "North? How do you know?",
                 "And I'm John Snow. Stop joking. Are you sure about this info?",
                 "No... sadly :( I'll probably go to the north.",
                 "Thanks :) Hopefully."
                ],
        starts:["Hey Tracer! Whatsup?"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Sean: {
        follows:["Hey Sean. I'm great. Hows your business?",
                 "Why? What happened?",
                 "Tell me!",
                 "Who is Pathay? Why didn't you call police for help?",
                 "I knew it. A tribe member doing what tribe members do best, bully others. I'll teach him a lesson by defeating him in a Roshambo battle.",
                 "Don't decide the winner before the battle. Atleast I want to try.",
                 "Yup, I will. Thanks."
                ],
        starts:["Hey Sean! Whatsup?"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Pathay:{

        follows:[],
        starts:[],
        battleAccept:["No, this isn't your property. This is my friend Sean's property.",
                      "I've got big hands as well. I challenge you for a Roshambo battle.",
                      "One tribe defeated is one tribe less. Lets go"],
        battleAsk:["I want to challenge you for a battle!"],
        battleWin:["Not for long. I'll soon defeat your boss."],
        battleLose:["I'm pretty sure you cheated. I'll be back."],
    },

    Chop:{

        follows:[],
        starts:[],
        battleAccept:["Do I have a choice?"],
        battleAsk:["Do you wanna battle?"],
        battleWin:["You are pretty good. I got lucky."],
        battleLose:["No! I underestimated you. See you next time."],
    },

    Molly: {
        follows:["Hey Molly. Why are you outside the library?",
                 "Have they occupied the library as well? I thought its just the bakery and the chinese van.",
                 "Don't worry. I'll soon defeat their boss.",
                 "Really! I didn't know that. I should go inside and battle them. Wish me luck.",
                 "Thanks!"],
        starts:["Hey Molly! Whatsup?"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Jordan: {
        follows:[],
        starts:[],
        battleAccept:["Yeah sure, lets go!"],
        battleAsk:["Hey! do you wanna battle?"],
        battleWin:["Thanks mate!"],
        battleLose:["I'll be back in no time. See you then."],
    },

    Grindel:{
        follows:[],
        starts:[],
        battleAccept:["Do I have a choice?"],
        battleAsk:["Do you wanna battle?"],
        battleWin:["You are pretty good. I got lucky."],
        battleLose:["No! I underestimated you. See you next time."],
    },

    Tori:{
        follows:[],
        starts:[],
        battleAccept:["Definitely! I need to practice as well."],
        battleAsk:["Do you wanna battle?"],
        battleWin:["Losers will be losers"],
        battleLose:["I underestimated you. See you next time."],
    },

    Ghissu: {
        follows:["Hey Ghissu. Done with all the ghisai?",
                 "Molly told me the tribe has occupied the library as well. I'm looking for them.",
                 "Atleast you have a source of entertainment now. Haha. Jokes aside, where are they?",
                 "I should have known. Thanks! See you after the battle.",
                 "Haha. Bbye."],
        starts:["Hey Ghissu! Whatsup?"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Razor:{

        follows:[],
        starts:[],
        battleAccept:["Its a public TV, you can't watch something private here.",
                      "Not for long. Soon I'll defeat your boss.",
                      "You stole words from my mouth. I accept the challenge.",
                      "Stop talking and start battling!"],
        battleAsk:["I want to challenge you for a battle!"],
        battleWin:["Not for long. I'll soon defeat your boss."],
        battleLose:["I'm pretty sure you cheated.", "I'll be back in no time."],
    },

    Prick:{
        follows:[],
        starts:[],
        battleAccept:["Definitely! I need to practice as well."],
        battleAsk:["Do you wanna battle?"],
        battleWin:["Losers will be losers"],
        battleLose:["I underestimated you. See you next time."],
    },

    LT: {
        follows:["Okay... I get it."],
        starts:["Hey! Can I play?"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Rose: {
        follows:["Are they tribe members?",
                 "As expected. Okay, I'll try to get her back.",
                 "No problem."],
        starts:["Hey! Did you get sparkle back?"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },


    Snyder:{

        follows:[],
        starts:[],
        battleAccept:["Stop disturbing the dog. Leave her alone!",
                      "Just like I'll teach your boss a lesson?", 
                      "I'll soon defeat him in Roshambo. But, let me defeat you first!",
                      "If I win, you free the dog!",
                      "Challenge accepted!"],
        battleAsk:["I want to challenge you for a battle."],
        battleWin:["Not for long. I'll soon defeat your boss."],
        battleLose:["I'm pretty sure you cheated.", "I'll be back in no time."],
    },

    Kaloo: {
        follows:["Okay...."],
        starts:["Awwww......kaloooooo."],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Goku: {
        follows:["Nevermind...."],
        starts:["Awwww......cutie. Come here....."],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Misty: {
        follows:["Nevermind...."],
        starts:["Awwww....Come here....."],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Trigger: {
        follows:["Nevermind...."],
        starts:["Awwww......cutie. Come here....."],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Max:{
        follows:[],
        starts:[],
        battleAccept:["Definitely! I need to practice as well."],
        battleAsk:["Do you wanna battle?"],
        battleWin:["Losers will be losers"],
        battleLose:["You got real skills mate!"],
    },


    Maty: {
        follows:["Hey Maty! Yeah. How have you been?", 
                 "On my quest to defeat the tribe boss.",
                 "Thanks :)! I should go and defeat him.",
                 "Hehe. Thanks!"],
        starts:["Hey Maty!"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Damon:{

        follows:[],
        starts:[],
        battleAccept:["Do I have a choice?"],
        battleAsk:["Do you wanna battle?"],
        battleWin:["You are pretty good. I got lucky."],
        battleLose:["No! I underestimated you. See you next time."],
    },


    Tegan:{

        follows:[],
        starts:[],
        battleAccept:["No! I was looking for you.",
                      "So that I can defeat you first, before your boss!",
                      "Challenge accepted! Let me throw you out of our town haha."],
        battleAsk:["I want to challenge you for a battle!"],
        battleWin:["Not for long. I'll soon defeat your boss."],
        battleLose:["I'm pretty sure you cheated.", "I'll be back in no time."],
    },

    Hunt:{

        follows:[],
        starts:[],
        battleAccept:["Do I have a choice?"],
        battleAsk:["Do you wanna battle?"],
        battleWin:["You are pretty good. I got lucky."],
        battleLose:["No! I underestimated you. See you next time."],
    },


    Fattu: {
        follows:["Why? The tribe boss isn't inside?",
                 "She!??! WTF. I'm going in.",
                 "Don't worry about me."],
        starts:["Hey Fattu!"],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Rock: {
        follows:["Nevermind...."],
        starts:["Awwww......cutie. Come here....."],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Paper: {
        follows:["Nevermind...."],
        starts:["Awwww......cutie. Come here....."],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Scissors: {
        follows:["Nevermind...."],
        starts:["Awwww......cutie. Come here....."],
        battleAccept:[],
        battleAsk:[],
        battleWin:[],
        battleLose:[],
    },

    Beast:{

        follows:[],
        starts:[],
        battleAccept:["Looking for the tribe boss. I want to battle her in Roshambo. Do you where is she?",
                      "Ohh, my bad. How can I miss the biggest clue lol. Btw I'm $PLAYERNAME. I came here to challenge you for a Roshambo battle.",
                      "There can be, like petting your cute cats.",
                      "Yeah, they don't seem friendly, just like you.",
                      "Yeah! Let's go!"],
        battleAsk:["I want to challenge you for a battle!"],
        battleWin:["Really? You aren't mad?",
                   "You're not as bad as I expected tbh.",
                   "So?? Am I the boss now? How does it work? How can I reset the rules?",
                   "I thought so. I thought that was the story of the game! When is the Roshambo championship?",
                   "He???",
                   "Wow. And what about my Eclairs?",
                   "Fuck it!"],
        battleLose:["I'll be back with more practice"],
    },
}

export const NPCDIALOGS = {
    Frank:{
        starts: ["Hey $PLAYERNAME! Whatsup.", "Long time no see. Where are you these days?", 
                "I'm preparing for this year's RoShamBo competition.", 
                "BTW, your father is waiting for you inside. You should go and meet him.", 
                "Sure, see you."],
        follows: ["I'm great. You talked to your father right!",
                  "They are dangerous! Try to stay away from them!"],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Dad:{
        starts: ["Hey kiddo! Glad you're back. It feels great seeing you!",
                 "Did you notice anything weird outside?", 
                 "Its the markov tribe! Their boss won the Roshambo championship last year. Since then they have imposed new Roshambo rules in the town.",
                 "Now there is a level system in Roshambo. Every Roshambo player starts at level 1 and can go till level 5.",
                 "You can only battle a player who is at a lower or same level or 1 level higher than yours.",
                 "Yes, and thats why we need to overthrow this tribe.",
                 "We need to defeat their boss, only then we can remove these horrible rules.",
                 "Thats my kid! Look around the town for some Roshambo battlers for practice. Battle them to gain exp and level up.",
                 "Your baby brother missed you! Don't forget to play with him.",
                 "Btw, your favourite Big Chill cakery has opened nearby. You should check it out."
                ],
        follows: ["Key kiddo! You should probably go and defeat the tribe!"],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Joey:{
        starts: [],
        follows: [],
        battleAsk: ["I wanna play!!!"],
        battleAcceptNeverDefeated:["Yayayayay! I'll defeat you again!"],
        battleAcceptDefeated:["Yes! I love defeating you!"],
        battleDecline:["I don't think you're on my level. Go and Practice"],
        battleLose:["You cheated!!!!"],
        battleWin: ["I'm the best!!"],
    },


    Tia:{
        starts: ["Hey $PLAYERNAME! Whatsup!", 
                 "You won't be able to get anything from here.", 
                 "There is a markov tribe member inside. If you want an eclair, you need to defeat him in Roshambo first.", 
                 "Everything belongs to them now. They have weird rules tbh.",
                 "I hope you have enough practice. You can battle my friend Samantha, she is inside the bakery."
                ],
        follows: ["I hope you defeat the tribe member."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Nathan:{
        starts: [],
        follows: [],
        battleAsk: ["You won't be able to defeat me. Do you have the guts to battle?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice"],
        battleLose:["You are great! Cheers!."],
        battleWin: ["You're aweful. You need to practice."],
    },

    John:{
        starts: [],
        follows: [],
        battleAsk: ["You won't be able to defeat me. Do you have the guts to battle?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice"],
        battleLose:["You are great! Cheers!."],
        battleWin: ["You're aweful. You need to practice."],
    },

    Samantha:{
        starts: [],
        follows: [],
        battleAsk: ["Hey! Do you wanna battle? Winner gets a swiss roll :p"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice"],
        battleLose:["You are great! Now you need to defeat the tribe member to get the free swiss roll. Hehe.",
                     "Really! You'll get a brownie as well if you defeat him."],
        battleWin: ["Gosh! You're aweful. You need to practice. I don't think I'll ever get the swiss roll lol."],
    },

    Eden:{
        starts: [],
        follows: [],
        battleAsk: ["Hey you! I think you're new here.",
                    "Just an eclair? You can have one.",
                    "No, I was kidding. You need to defeat me in Roshambo first.",
                    "I like defeating overconfident kids, lets go!"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["This time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go, battle and level up."],
        battleLose:["You have defeated me, but you won't be able to defeat our boss.", 
                    "If you think you can get your eclair now, you are a fool!",
                    "Ah, I lied. You need to defeat our boss in order to change the rules. Hahahahaha.",
                    "Find him yourself. All the best. Hahahahahahahaha."],
        battleWin: ["Typical overconfident kid. You can never defeat me, nevermind our boss!!"],
    },

    Tracer:{
        starts: ["Hey $PLAYERNAME! Where are you heading towards?", 
                 "I heard he lives in a cave somewhere in the north.", 
                 "I'm the master of whisperers. Haha.", 
                 "Hehe. Do you have any other option?", 
                 "All the best. May the luck be with you."],
        follows: ["Ohh, you are still alive!"],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Sean:{
        starts: ["Hey $PLAYERNAME! Long time no see?", 
                 "Ummm...not great.",
                 "Ummm....",
                 "Pathay and his bully friends are not allowing me to run my business!", 
                 "He is a tribe member. That't why nobody is willing to help me.", 
                 "He's on level 4, I don't think you can defeat him. I don't want to give you any trouble.", 
                 "Okay, your call. But, be careful."],
        follows: ["Be careful of the tribe, $PLAYERNAME."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Pathay:{
        starts: [],
        follows: [],
        battleAsk: ["Hey kid! Stop wandering around here. This is tribe's property!",
                    "Your big mouth will lead you into trouble.",
                    "I can defeat you in 2 minutes. Challenge accepted."],
        battleAcceptNeverDefeated:["Again? Save your self respect!"],
        battleAcceptDefeated:["You won't be lucky this time."],
        battleDecline:["You need to level up, loser!"],
        battleLose:["You got lucky. Nevermind, this town still belongs to us!"],
        battleWin: ["You were a total waste of time."],
    },

    Chop:{
        starts: [],
        follows: [],
        battleAsk: ["Do you wanna test your Roshambo skills against a real player?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice."],
        battleLose:["Today is not my day. I should get some rest."],
        battleWin: ["Was this your first time lol?"],
    },

    Molly:{
        starts: ["Hey $PLAYERNAME. Glad you are here.",
                 "There's a lot of noise inside. The tribe members you know.",
                 "They are everywhere. We need to get rid of them.",
                 "First you need to defeat all of the tribe members. Only then you can battle their boss. I hope you knew this.",
                 "All the best! May the luck be with you."],
        follows: ["Not great. I hope you defeat the tribe soon."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Jordan:{
        starts: [],
        follows: [],
        battleAsk: ["You won't be able to defeat me. Do you have the guts to battle?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice"],
        battleLose:["You are great! Cheers!."],
        battleWin: ["You're aweful. You need to practice."],
    },

    Grindel:{
        starts: [],
        follows: [],
        battleAsk: ["Do you wanna test your Roshambo skills against a real player?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice."],
        battleLose:["Today is not my day. I should get some rest."],
        battleWin: ["Was this your first time lol?"],
    },

    Tori:{
        starts: [],
        follows: [],
        battleAsk: ["Test your Roshambo skills against a real player. Battle?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice."],
        battleLose:["So lucky you are! So lucky you are!"],
        battleWin: ["Was this your first time lol?"],
    },

    Ghissu:{
        starts: ["Hey $PLAYERNAME! Whatsup!", 
                 "No! still 4th revision remaining. BTW, what are you doing here?", 
                 "Yeah, they play all sorts of horrible music here, and particularly during daytime.",
                 "In the gameroom, first floor.",
                 "Hopefully your Roshambo is better than your sense of humour."
                ],
        follows: ["Hey! Get lost now. I have to study."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Razor:{
        starts: [],
        follows: [],
        battleAsk: ["Hey! Stop disturbing me! I watching something important.",
                    "Don't teach me the rules. I make the rules here.",
                    "Stop day dreaming you idiot. I challenge you for a Roshambo battle.",
                    "You won't dare to speak a word against the tribe after this."],
        battleAcceptNeverDefeated:["Again? Save your self respect!"],
        battleAcceptDefeated:["You won't be lucky this time."],
        battleDecline:["You need to level up, loser!"],
        battleLose:["You got lucky. Nevermind, this town still belongs to us!"],
        battleWin: ["You were a total waste of time.", "Now shut up and FO!"],
    },

    Prick:{
        starts: [],
        follows: [],
        battleAsk: ["Hey kid! Do you wanna battle?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice."],
        battleLose:["So lucky you are! So lucky you are!"],
        battleWin: ["Was this your first time lol?"],
    },

    LT:{
        starts: ["Hey you! Don't disturb Razor. He doesn't like interruptions in between a movie."],
        follows: ["Get lost from here."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Rose:{
        starts: ["Hey! Please help me get my sparkle back. Snyder and his friend are not letting her go.",
                 "Yes.",
                 "Thanks!"],
        follows: ["She' still with them! :("],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Snyder:{
        starts: [],
        follows: [],
        battleAsk: ["Hey you! stop disturbing us.",
                    "This isn't your dog, so stop bothering. Stay away from us, otherwise we'll teach you a lesson.",
                    "Hahahahaha. You can't touch even him!",
                    "Really? Challenge accepted!",
                    "If you lose, you stay away from us!"],
        battleAcceptNeverDefeated:["Again? Save your self respect!"],
        battleAcceptDefeated:["You won't be lucky this time."],
        battleDecline:["You need to level up, loser!"],
        battleLose:["You got lucky. Nevermind, this town still belongs to us!"],
        battleWin: ["You were a total waste of time.", "Now get lost!"],
    },

    Kaloo:{
        starts: ["Meoww..."],
        follows: ["....Meow.....Fuck off.....Meow..."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Goku:{
        starts: ["Meoww...Meoww..."],
        follows: ["Grhhhhhh....."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Misty:{
        starts: ["Meoww...Meoww..."],
        follows: ["Grhhhhhh....."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Trigger:{
        starts: ["Meoww....You'll die...Meoww...."],
        follows: ["Grhhhhhh.....Step aside....."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Max:{
        starts: [],
        follows: [],
        battleAsk: ["Hey! Do you wanna battle?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice."],
        battleLose:["So lucky you are! So lucky you are!"],
        battleWin: ["Was this your first time lol?"],
    },

    

    Maty:{
        starts: ["Hey $PLAYERNAME! Long time!", 
                 "I'm great! Never seen you on this side of town before?", 
                 "You're living dangerously. Btw, you can find one of the tribe members near the hammock by the pool.",
                 "Yeah. Before he creates more havoc near the hammock lol. All the best"],
        follows: ["Hey $PLAYERNAME. I hope you defeat the boss."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },
    
    Damon:{
        starts: [],
        follows: [],
        battleAsk: ["Do you wanna test your Roshambo skills against a real player?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice."],
        battleLose:["Today is not my day. I should get some rest."],
        battleWin: ["Was this your first time lol?"],
    },

    Tegan:{
        starts: [],
        follows: [],
        battleAsk: ["Hey kid! I heard you are looking for the tribe boss.", 
                    "Me? Why?",
                    "Keep dreaming kid. I challenge you for a battle. Let me bring you down to earth haha."],
        battleAcceptNeverDefeated:["Again? Save your self respect unless you want to go underground lol."],
        battleAcceptDefeated:["You won't be lucky this time."],
        battleDecline:["You need to level up, loser!"],
        battleLose:["You got lucky. Nevermind, this town still belongs to us!"],
        battleWin: ["You were a total waste of time.", "Now shut up and FO!"],
    },


    Hunt:{
        starts: [],
        follows: [],
        battleAsk: ["Do you wanna test your Roshambo skills against a real player?"],
        battleAcceptNeverDefeated:["How many times you wanna lose!!"],
        battleAcceptDefeated:["Yeah, sure. But, this time you won't be lucky!"],
        battleDecline:["I don't think you're on my level. Go and Practice."],
        battleLose:["Today is not my day. I should get some rest."],
        battleWin: ["Was this your first time lol?"],
    },

    Fattu:{
        starts: ["Dude! Stop here. Don't go inside.",
                 "She is. Thats why.",
                 "You will definitely die, sexist."],
        follows:["You are still alive!"],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Rock:{
        starts: ["Meoww....You'll die...Meoww...."],
        follows: ["Meoww...Hail Markov...Meoww..."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Paper:{
        starts: ["Meoww....You'll die...Meoww...."],
        follows: ["Meoww..Markov greater Bayesian....Meoww..."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Scissors:{
        starts: ["Meoww....You'll die...Meoww...."],
        follows: ["Meoww...Hail Markov...Meoww..."],
        battleAsk:[],
        battleAcceptNeverDefeated:[],
        battleAcceptDefeated:[],
        battleDecline:[],
        battleLose:[],
        battleWin:[],
    },

    Beast:{
        starts: [],
        follows: [],
        battleAsk: ["Hey! What are you doing here?",
                    "Is there anyone else over here wearing a semi-naked vamp costume? I'm the boss and my name is Beast.",
                    "I know. There can be no other reason for you to be here.",
                    "Oh you like cats? The black one is Rock, the white one is Paper and the ginger one is Scissors. Stay away from them.",
                    "I thought you were here for the battle. Just being professional."],
        battleAcceptNeverDefeated:["I hope you are prepared this time."],
        battleAcceptDefeated:["You won't be lucky this time."],
        battleDecline:["You need to defeat all my tribe members first! Plus you need to be on Level 5."],
        battleLose:["You defeated me all fair and square. Kudos to you.",
                     "No, you are a deserving winner. And I'm not a sore loser.",
                     "Now I feel much better lol.",
                     "You cannot just reset the rules! You need to defeat me in the Roshambo championship. You thought you could be the tribe boss on the basis of a friendly battle?",
                     "Next year. He needs to start coding for the that.",
                     "The developer of this game.",
                     "Ask the developer."],
        battleWin: ["You really thought you got a chance here lol."],
    },
    
}