export const UPDATE_PLAYER_POSITION = "UPDATE_PLAYER_POSITION";
export const UPDATE_PLAYER_DIRECTION = "UPDATE_PLAYER_DIRECTION";
export const UPDATE_PLAYER_ANIMATION = "UPDATE_PLAYER_ANIMATION";
export const ADD_MAP = "ADD_MAP";
export const MAP_LOADING = "MAP_LOADING";
export const UPDATE_MAP_ORIGIN = "UPDATE_MAP_ORIGIN";