export const UPDATE_PLAYER_POSITION = "UPDATE_PLAYER_POSITION";
export const UPDATE_PLAYER_DIRECTION = "UPDATE_PLAYER_DIRECTION";
export const UPDATE_PLAYER_ANIMATION = "UPDATE_PLAYER_ANIMATION";
export const UPDATE_NEARBY_NPC = "UPDATE_NEARBY_NPC";
export const UPDATE_NEARBY_GAMEOBJ = "UPDATE_NEARBY_GAMEOBJ";
export const UPDATE_NEARBY_PORTAL = "UPDATE_NEARBY_PORTAL";

export const ADD_MAP = "ADD_MAP";
export const MAP_LOADING = "MAP_LOADING";
export const UPDATE_MAP_ORIGIN = "UPDATE_MAP_ORIGIN";

export const UPDATE_NPC_POSITION = "UPDATE_NPC_POSITION";
export const UPDATE_NPC_DIRECTION = "UPDATE_NPC_DIRECTION";
export const UPDATE_NPC_ANIMATION = "UPDATE_NPC_ANIMATION";
export const RESET_NPC_WAITING = "RESET_NPC_WAITING";

export const SET_DIALOG_STATUS = "SET_DIALOG_STATUS";
export const RESET_DIALOG_STATUS = "RESET_DIALOG_STATUS";
export const NEXT_DIALOG = "NEXT_DIALOG";

export const TOGGLE_INVENTORY_DISPLAY = "TOGGLE_INVENTORY_DISPLAY";
export const ADD_OBJECT_TO_INVENTORY = "ADD_OBJECT_TO_INVENTORY";

export const SAVE_STATE_INITIATED = "SAVE_STATE_INITIATED";
export const SAVE_STATE = "SAVE_STATE";
export const SAVE_STATE_END = "SAVE_STATE_END";
export const RESTORE_STATE = "RESTORE_STATE";

export const TOGGLE_BATTLE = "TOGGLE_BATTLE";
export const SUBMIT_MOVES = "SUBMIT_MOVES";